services:
  - type: web
    name: big-backend
    env: python
    buildCommand: "npm install --prefix data_cleaner && npm run build --prefix data_cleaner && pip install -r backend/requirements.txt"
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_PATH
        value: /data/patent_database.db
